language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pycodestyle  --cov-report term --cov=torchtrainer --max-line-length=120
  - pytest
after_success:
  - codecov